steps:
- name: 'gcr.io/google.com/cloudsdktool/cloud-sdk'
  entrypoint: 'bash'
  args:
    - '-c'
    - |
      bq query --use_legacy_sql=false < CICD-basics/BQ_SQL_DEPLOY/sql/create_customer.sql
options:
  logging: CLOUD_LOGGING_ONLY
