steps:
- name: 'gcr.io/google.com/cloudsdktool/cloud-sdk'
  entrypoint: 'bash'
  args:
    - '-c'
    - |
      ACCESS_TOKEN=$$(gcloud auth print-access-token)

      # Create compilation result
      COMPILATION_RESP=$$(curl -s -X POST \
      -H "Authorization: Bearer $$ACCESS_TOKEN" \
      -H "Content-Type: application/json" \
      -d '{"gitCommitish":"main"}' \
      "https://dataform.googleapis.com/v1beta1/projects/project-cb5a77af-6ec0-433b-a14/locations/us-central1/repositories/ravi-dataform-prac/compilationResults")

      echo "$$COMPILATION_RESP"

      COMPILATION_RESULT=$$(echo "$$COMPILATION_RESP" | grep -o '"name": *"[^"]*"' | cut -d'"' -f4)

      echo "Compilation Result:"
      echo "$$COMPILATION_RESULT"

      # Invoke only customer
      curl -X POST \
      -H "Authorization: Bearer $$ACCESS_TOKEN" \
      -H "Content-Type: application/json" \
      -d "{
        \"compilationResult\": \"$$COMPILATION_RESULT\",
        \"invocationConfig\": {
          \"includedTargets\": [
            {
              \"database\": \"project-cb5a77af-6ec0-433b-a14\",
              \"schema\": \"demo\",
              \"name\": \"customer\"
            }
          ]
        }
      }" \
      "https://dataform.googleapis.com/v1beta1/projects/project-cb5a77af-6ec0-433b-a14/locations/us-central1/repositories/ravi-dataform-prac/workflowInvocations"

options:
  logging: CLOUD_LOGGING_ONLY
