steps:
- name: 'gcr.io/google.com/cloudsdktool/cloud-sdk'
  entrypoint: 'bash'
  args:
    - '-c'
    - |
      gcloud dataform repositories list \
      --location=us-central1
options:
  logging: CLOUD_LOGGING_ONLY
